// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/petlog/internal/config"
	"github.com/blackhorseya/petlog/internal/domain/repository"
	"github.com/blackhorseya/petlog/internal/infra/mongodb"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func newInjector(config2 config.Config) (*injector, func(), error) {
	database, cleanup, err := mongodb.NewDatabase(config2)
	if err != nil {
		return nil, nil, err
	}
	hospitalRepository := mongodb.NewHospitalRepository(database)
	geocodeService := provideGoogleGeocodeService(config2)
	mainInjector := &injector{
		config:         config2,
		mongoDatabase:  database,
		hospitalRepo:   hospitalRepository,
		geocodeService: geocodeService,
	}
	return mainInjector, func() {
		cleanup()
	}, nil
}

// wire.go:

// injector 依賴注入容器
type injector struct {
	config         config.Config
	mongoDatabase  *mongo.Database
	hospitalRepo   repository.HospitalRepository
	geocodeService GeocodeService
}
