// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/dashboard/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "回傳目前登入使用者的寵物數量與健康日誌數量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "首頁快速概覽",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetDashboardOverviewResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/expenses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "依條件查詢費用紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "查詢費用紀錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "pet_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分類",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起始日期 (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "結束日期 (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListExpensesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListExpensesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListExpensesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListExpensesResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "建立一筆新的費用紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "新增費用紀錄",
                "parameters": [
                    {
                        "description": "費用資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateExpenseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateExpenseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateExpenseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateExpenseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateExpenseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/expenses/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查詢本月總支出、分類統計等摘要",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "查詢費用摘要",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "pet_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseSummaryResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseSummaryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseSummaryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/expenses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取得指定 ID 的費用紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "取得單筆費用紀錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "費用ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetExpenseResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "編輯指定 ID 的費用紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "編輯費用紀錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "費用ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "費用資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateExpenseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateExpenseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateExpenseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateExpenseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateExpenseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateExpenseResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "刪除指定 ID 的費用紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "刪除費用紀錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "費用ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteExpenseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteExpenseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteExpenseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteExpenseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteExpenseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物 ID 和可選的日期範圍列出健康日誌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-logs"
                ],
                "summary": "列出寵物的健康日誌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物 ID",
                        "name": "pet_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "開始日期 (RFC3339 格式)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "結束日期 (RFC3339 格式)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListHealthLogsByPetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "為指定的寵物建立一筆新的健康日誌紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-logs"
                ],
                "summary": "建立健康日誌",
                "parameters": [
                    {
                        "description": "健康日誌資訊",
                        "name": "healthLog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateHealthLogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateHealthLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/health-logs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取得指定 ID 的健康日誌詳細資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-logs"
                ],
                "summary": "根據 ID 取得健康日誌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "健康日誌 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetHealthLogByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新指定 ID 的健康日誌資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-logs"
                ],
                "summary": "更新健康日誌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "健康日誌 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的健康日誌資訊",
                        "name": "healthLog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateHealthLogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateHealthLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "刪除指定 ID 的健康日誌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-logs"
                ],
                "summary": "刪除健康日誌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "健康日誌 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteHealthLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/hospitals": {
            "get": {
                "description": "根據關鍵字、縣市、狀態等條件搜尋醫院，支援分頁和排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hospitals"
                ],
                "summary": "搜尋醫院",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜尋關鍵字（醫院名稱、地址、獸醫師）",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "縣市篩選",
                        "name": "county",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "狀態篩選（開業、歇業等）",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "執照類型篩選（動物醫院、動物診所）",
                        "name": "license_type",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "座標緯度（用於距離排序）",
                        "name": "latitude",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "座標經度（用於距離排序）",
                        "name": "longitude",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "搜尋半徑（公里）",
                        "name": "radius",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "頁碼（預設1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每頁數量（預設20）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方式（distance, name）",
                        "name": "sort_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.SearchHospitalsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/hospitals/nearby": {
            "get": {
                "description": "根據使用者位置座標搜尋指定半徑內的醫院",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hospitals"
                ],
                "summary": "查詢附近醫院",
                "parameters": [
                    {
                        "type": "number",
                        "description": "使用者位置緯度",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "使用者位置經度",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "搜尋半徑（公里，預設10）",
                        "name": "radius_km",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "結果數量限制（預設50）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListNearbyHospitalsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/hospitals/{id}": {
            "get": {
                "description": "根據醫院ID取得完整的醫院資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hospitals"
                ],
                "summary": "取得醫院詳細資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "醫院ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetHospitalDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/medical-records": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物 ID 和可選的日期範圍列出醫療記錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical-records"
                ],
                "summary": "列出寵物的醫療記錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物 ID",
                        "name": "pet_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "開始日期 (RFC3339 格式)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "結束日期 (RFC3339 格式)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListMedicalRecordsByPetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "為指定的寵物建立一筆新的醫療記錄（疫苗、驅蟲、藥物治療、獸醫檢查等）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical-records"
                ],
                "summary": "建立醫療記錄",
                "parameters": [
                    {
                        "description": "醫療記錄資訊",
                        "name": "medicalRecord",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateMedicalRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateMedicalRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/medical-records/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據醫療記錄 ID 取得詳細資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical-records"
                ],
                "summary": "取得醫療記錄詳情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "醫療記錄 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetMedicalRecordResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據醫療記錄 ID 更新現有醫療記錄資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical-records"
                ],
                "summary": "更新醫療記錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "醫療記錄 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "要更新的醫療記錄資訊",
                        "name": "medicalRecord",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateMedicalRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdateMedicalRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據醫療記錄 ID 刪除醫療記錄資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical-records"
                ],
                "summary": "刪除醫療記錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "醫療記錄 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeleteMedicalRecordResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/pets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取得目前使用者擁有的所有寵物列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "列出所有寵物",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListPetsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "為使用者建立一筆新的寵物資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "建立新寵物",
                "parameters": [
                    {
                        "description": "寵物資訊",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreatePetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/pets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物ID取得詳細資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "取得寵物資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetPetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物ID更新現有寵物資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "更新寵物資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "要更新的寵物資訊",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdatePetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物ID刪除寵物資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "刪除寵物",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeletePetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoint.Coordinates": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "endpoint.CreateExpenseRequest": {
            "type": "object",
            "required": [
                "amount",
                "category",
                "date",
                "pet_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "minimum": 1
                },
                "category": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                }
            }
        },
        "endpoint.CreateExpenseResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "expense": {
                    "$ref": "#/definitions/model.Expense"
                }
            }
        },
        "endpoint.CreateHealthLogRequest": {
            "type": "object",
            "properties": {
                "behaviour_notes": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "food_gram": {
                    "type": "integer"
                },
                "litter_notes": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "endpoint.CreateHealthLogResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "health_log": {
                    "$ref": "#/definitions/model.HealthLog"
                }
            }
        },
        "endpoint.CreateMedicalRecordRequest": {
            "type": "object",
            "required": [
                "date",
                "description",
                "pet_id",
                "type"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dosage": {
                    "type": "string"
                },
                "next_due_date": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.MedicalRecordType"
                }
            }
        },
        "endpoint.CreateMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "medical_record": {
                    "$ref": "#/definitions/model.MedicalRecord"
                }
            }
        },
        "endpoint.CreatePetRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "microchip_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "endpoint.CreatePetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "pet": {
                    "$ref": "#/definitions/model.Pet"
                }
            }
        },
        "endpoint.DeleteExpenseResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "endpoint.DeleteHealthLogResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "endpoint.DeleteMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "endpoint.DeletePetResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "endpoint.GetDashboardOverviewResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "health_record_count": {
                    "description": "健康日誌數量\nexample: 10",
                    "type": "integer"
                },
                "pet_count": {
                    "description": "寵物數量\nexample: 2",
                    "type": "integer"
                }
            }
        },
        "endpoint.GetExpenseResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "expense": {
                    "$ref": "#/definitions/model.Expense"
                }
            }
        },
        "endpoint.GetExpenseSummaryResponse": {
            "type": "object",
            "properties": {
                "category_stats": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "error": {},
                "recent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Expense"
                    }
                },
                "total_amount": {
                    "type": "integer"
                }
            }
        },
        "endpoint.GetHealthLogByIDResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "health_log": {
                    "$ref": "#/definitions/model.HealthLog"
                }
            }
        },
        "endpoint.GetHospitalDetailResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "hospital": {
                    "$ref": "#/definitions/endpoint.HospitalDTO"
                }
            }
        },
        "endpoint.GetMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "medical_record": {
                    "$ref": "#/definitions/model.MedicalRecord"
                }
            }
        },
        "endpoint.GetPetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "pet": {
                    "$ref": "#/definitions/model.Pet"
                }
            }
        },
        "endpoint.HospitalDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/endpoint.Coordinates"
                },
                "county": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issued_date": {
                    "type": "string"
                },
                "license_no": {
                    "type": "string"
                },
                "license_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "veterinarian": {
                    "type": "string"
                }
            }
        },
        "endpoint.ListExpensesResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Expense"
                    }
                }
            }
        },
        "endpoint.ListHealthLogsByPetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "health_logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HealthLog"
                    }
                }
            }
        },
        "endpoint.ListMedicalRecordsByPetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "medical_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MedicalRecord"
                    }
                }
            }
        },
        "endpoint.ListNearbyHospitalsResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "hospitals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/endpoint.HospitalDTO"
                    }
                }
            }
        },
        "endpoint.ListPetsResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Pet"
                    }
                }
            }
        },
        "endpoint.SearchHospitalsResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "hospitals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/endpoint.HospitalDTO"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "stats": {
                    "$ref": "#/definitions/query.SearchStats"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "endpoint.UpdateExpenseRequest": {
            "type": "object",
            "required": [
                "amount",
                "category",
                "date",
                "pet_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "minimum": 1
                },
                "category": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                }
            }
        },
        "endpoint.UpdateExpenseResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "expense": {
                    "$ref": "#/definitions/model.Expense"
                }
            }
        },
        "endpoint.UpdateHealthLogRequest": {
            "type": "object",
            "properties": {
                "behaviour_notes": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "food_gram": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "litter_notes": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "endpoint.UpdateHealthLogResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "health_log": {
                    "$ref": "#/definitions/model.HealthLog"
                }
            }
        },
        "endpoint.UpdateMedicalRecordRequest": {
            "type": "object",
            "required": [
                "date",
                "description",
                "pet_id",
                "type"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dosage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "next_due_date": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.MedicalRecordType"
                }
            }
        },
        "endpoint.UpdateMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "medical_record": {
                    "$ref": "#/definitions/model.MedicalRecord"
                }
            }
        },
        "endpoint.UpdatePetRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "microchip_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "endpoint.UpdatePetResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "model.Expense": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.HealthLog": {
            "type": "object",
            "properties": {
                "behaviour_notes": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "food_gram": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "litter_notes": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "model.MedicalRecord": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dosage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "next_due_date": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.MedicalRecordType"
                }
            }
        },
        "model.MedicalRecordType": {
            "type": "string",
            "enum": [
                "vaccination",
                "deworming",
                "medication",
                "vet_visit",
                "other"
            ],
            "x-enum-varnames": [
                "RecordTypeVaccination",
                "RecordTypeDeworming",
                "RecordTypeMedication",
                "RecordTypeVetVisit",
                "RecordTypeOther"
            ]
        },
        "model.Pet": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "microchip_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "query.SearchStats": {
            "type": "object",
            "properties": {
                "by_county": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "by_license_type": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "by_status": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "total_hospitals": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PetLog API",
	Description:      "寵物健康記錄管理系統 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
