// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health-logs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "為指定的寵物建立一筆新的健康日誌紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-logs"
                ],
                "summary": "建立健康日誌",
                "parameters": [
                    {
                        "description": "健康日誌資訊",
                        "name": "healthLog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateHealthLogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreateHealthLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/pets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取得目前使用者擁有的所有寵物列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "列出所有寵物",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListPetsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "為使用者建立一筆新的寵物資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "建立新寵物",
                "parameters": [
                    {
                        "description": "寵物資訊",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.CreatePetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/pets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物ID取得詳細資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "取得寵物資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetPetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物ID更新現有寵物資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "更新寵物資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "要更新的寵物資訊",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.UpdatePetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根據寵物ID刪除寵物資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "刪除寵物",
                "parameters": [
                    {
                        "type": "string",
                        "description": "寵物ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DeletePetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoint.CreateHealthLogRequest": {
            "type": "object",
            "properties": {
                "behaviour_notes": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "food_gram": {
                    "type": "integer"
                },
                "litter_notes": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "endpoint.CreateHealthLogResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "health_log": {
                    "$ref": "#/definitions/model.HealthLog"
                }
            }
        },
        "endpoint.CreatePetRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "microchip_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "endpoint.CreatePetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "pet": {
                    "$ref": "#/definitions/model.Pet"
                }
            }
        },
        "endpoint.DeletePetResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "endpoint.GetPetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "pet": {
                    "$ref": "#/definitions/model.Pet"
                }
            }
        },
        "endpoint.ListPetsResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Pet"
                    }
                }
            }
        },
        "endpoint.UpdatePetRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "microchip_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "endpoint.UpdatePetResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "model.HealthLog": {
            "type": "object",
            "properties": {
                "behaviour_notes": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "food_gram": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "litter_notes": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "model.Pet": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "microchip_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PetLog API",
	Description:      "寵物健康記錄管理系統 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
