basePath: /
host: localhost:8080
info:
  contact: {}
  description: 寵物健康記錄管理系統 API
  title: PetLog API
  version: "0.1"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
