name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      # PR 時部署到 int
      - name: Deploy to int (for PR)
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/deploy-lambda
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          stage: int
          serverless-access-key: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      # main branch push 時部署到 prod
      - name: Deploy to prod (for main push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/deploy-lambda
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          stage: prod
          serverless-access-key: ${{ secrets.SERVERLESS_ACCESS_KEY }}
